name: CI - Backend

on:
  push:
    paths:
      - "apps/api/**"
  pull_request:
    paths:
      - "apps/api/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: payflow
          POSTGRES_PASSWORD: payflow
          POSTGRES_DB: payflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Rodar lint
        run: npm run lint

      - name: Rodar testes
        run: npm run test
        env:
          DATABASE_URL: postgresql://payflow:payflow@localhost:5432/payflow
