name: CI - Backend

on:
  push:
    paths:
      - "apps/api/**"
  pull_request:
    paths:
      - "apps/api/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Rodar build
        run: npm run build
        env:
          DATABASE_URL: "file:./dev.db"